### ISSUE TITLE
Pinned requirements unused

### ISSUE THREAD

**Issue by lkubb** [saltstack/salt-extension#41]
Currently, the generated project contains hooks for generating pinned requirements for `tests`, `docs` and `lint`. The `noxfile.py` does not account for them (`tests`, `docs`) and `lint` is generally not used by anything.

I think it would make sense to decide whether the ~tests and~ docs generation and linting should use pinned requirements ~(I tend to agree)~ and then, depending on the decision, either make `nox` use them or remove the unnecessary scaffolding.

Edit: For context, the usage of pinned requirements was removed in https://github.com/saltstack/salt-extension/pull/4

Edit2: After some consideration, I don't think the test requirements should be pinned in the current state since that would disallow testing against different Salt versions. With the tests requirements unpinned, I'm not sure reintroducing pinning for other domains makes sense and tend to think it should be removed completely. That would also allow easily migrating to `pyproject.toml`.

So the question should be:
Should we pin test requirements per Python/OS/Salt version combination or just remove pinning completely?

**Comment by ScriptAutomate** [comment]
**Salt Project / VMware has ended active development of this project, this repository will no longer be updated.**

The community has created and maintained a better alternative to the development of Salt extensions: [salt-extensions/salt-extension-copier](https://github.com/salt-extensions/salt-extension-copier) (Create and maintain Salt extensions using Copier)
