### ISSUE TITLE
A flag to disable coverage

### ISSUE THREAD

**Issue by max-arnold** [saltstack/salt-extension#46]
The default [`noxfile.py`](https://github.com/saltstack/salt-extension/blob/main/src/saltext/cli/project/noxfile.py.j2) has no means to disable coverage reports (unlike the Salt test suite where we have the `coverage=False` session flag).

It would be very useful to have an ability to disable coverage to speedup the local test development process

**Comment by ScriptAutomate** [comment]
**Salt Project / VMware has ended active development of this project, this repository will no longer be updated.**

The community has created and maintained a better alternative to the development of Salt extensions: [salt-extensions/salt-extension-copier](https://github.com/salt-extensions/salt-extension-copier) (Create and maintain Salt extensions using Copier)
