### ISSUE TITLE
Bootstrap Sphinx (or more detailed README/CONTRIBUTING) docs for baseline documentation

### ISSUE THREAD

**Issue by ScriptAutomate** [saltstack/salt-extension#5]
This python project is undocumented and could use extra details on usage.

References:

- [Salt Extensions: PDF of Slide Deck](https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqblhIYkJ[…]content%2Fuploads%2F2021%2F03%2F2021-3-26-salt-extensions.pdf)
- [YouTube video on `salt-extension`](https://www.youtube.com/watch?v=hhomJkwxK3Q)

**Comment by waynew** [comment]
Also add https://saltstackcommunity.slack.com/archives/C8832QN4U/p1629085392024500?thread_ts=1629074366.024400&cid=C8832QN4U (elevator pitch) to the README. Why a salt extension? What is it good for? What pain points does it alleviate? What problems does it solve? Why is it better or different than simply adding custom execution modules?

**Comment by ScriptAutomate** [comment]
> Also add https://saltstackcommunity.slack.com/archives/C8832QN4U/p1629085392024500?thread_ts=1629074366.024400&cid=C8832QN4U (elevator pitch) to the README. Why a salt extension? What is it good for? What pain points does it alleviate? What problems does it solve? Why is it better or different than simply adding custom execution modules?

I've now extended `README.md` to at least include the elevator pitch via #8 

Other useful docs that are needed:

- Tutorials on using salt-extension to make new
  - exec modules
  - state modules
  - etc.
- How to import/add a salt-extension project into a salt environment/deployment
- How to use `nox` in a variety of ways (to gen docs from `.rst`, to gen API docs, to gen changelog, perhaps have a nox command to tag a new release and compile a `tar.gz` for publishing to pypi, etc.)

**Comment by ScriptAutomate** [comment]
**Salt Project / VMware has ended active development of this project, this repository will no longer be updated.**

The community has created and maintained a better alternative to the development of Salt extensions: [salt-extensions/salt-extension-copier](https://github.com/salt-extensions/salt-extension-copier) (Create and maintain Salt extensions using Copier)
